# -*- coding: utf-8 -*-
"""SUPPLY_CHAIN_OPTIMIZATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XC_aGfB7GyVwO2451MWOwejRGOps4rOR
"""

# ================================
# 1. IMPORT LIBRARIES
# ================================
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

# ================================
# 2. LOAD DATA
# ================================
df = pd.read_csv("/content/shoe_sales.csv")

# ================================
# 3. STANDARDIZE COLUMN NAMES
# ================================
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# ================================
# 4. DATE HANDLING (FIXED)
# ================================
date_col = "snapshot_date"

df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

# Drop rows with invalid dates
df = df.dropna(subset=[date_col])

# Sort for time-series modeling
df = df.sort_values(by=date_col).reset_index(drop=True)

# ================================
# 5. REMOVE DUPLICATES
# ================================
df = df.drop_duplicates()

# ================================
# 6. HANDLE MISSING VALUES
# ================================
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
cat_cols = df.select_dtypes(include=["object"]).columns

num_imputer = SimpleImputer(strategy="median")
df[num_cols] = num_imputer.fit_transform(df[num_cols])

cat_imputer = SimpleImputer(strategy="most_frequent")
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

# ================================
# 7. ENCODE CATEGORICAL FEATURES
# ================================
label_encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# ================================
# 8. TIME FEATURES (SAFE)
# ================================
df["year"] = df[date_col].dt.year
df["month"] = df[date_col].dt.month
df["week"] = df[date_col].dt.isocalendar().week.astype(int)

# ================================
# 9. FINAL VALIDATION
# ================================
print("Final Shape:", df.shape)
print(df.head())
print(df.isnull().sum())

print(df.columns.tolist())

"""DATA ANALYSIS

"""

print("Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nStatistical Summary:\n")
df.describe()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df["total_sold"], bins=30)
plt.title("Distribution of Total Sold (Demand)")
plt.xlabel("Units Sold")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["unsold_inventory"], bins=30)
plt.title("Distribution of Unsold Inventory")
plt.xlabel("Units in Inventory")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["damaged_units"], bins=30)
plt.title("Distribution of Damaged Units")
plt.xlabel("Damaged Units")
plt.ylabel("Frequency")
plt.show()

monthly_demand = (
    df.groupby(["year", "month"])["total_sold"]
    .sum()
    .reset_index()
)

monthly_demand["date"] = pd.to_datetime(
    monthly_demand["year"].astype(str) + "-" +
    monthly_demand["month"].astype(str) + "-01"
)

plt.figure(figsize=(10,5))
plt.plot(monthly_demand["date"], monthly_demand["total_sold"])
plt.title("Monthly Demand Trend")
plt.xlabel("Date")
plt.ylabel("Total Units Sold")
plt.show()

month_avg = df.groupby("month")["total_sold"].mean()

plt.figure(figsize=(8,5))
month_avg.plot(kind="bar")
plt.title("Average Demand by Month")
plt.xlabel("Month")
plt.ylabel("Average Units Sold")
plt.show()

top_products = (
    df.groupby("product_name")["total_sold"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(9,5))
top_products.plot(kind="bar")
plt.title("Top 10 Products by Total Demand")
plt.xlabel("Product")
plt.ylabel("Units Sold")
plt.show()

import seaborn as sns

plt.figure(figsize=(10,6))
corr = df[
    ["total_sold", "unit_price", "sell_through_rate",
     "damage_rate", "unsold_inventory", "performance_score"]
].corr()

sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

"""FEATURE ENGINEERING

"""

# Target variable (Demand)
TARGET = "total_sold"

# Time column
DATE_COL = "snapshot_date"

# Columns to drop (leakage / not useful for forecasting)
drop_cols = [
    "estimated_revenue",     # derived from sales
    "sell_through_rate",     # depends on sold & inventory
    "damage_rate",           # derived metric
]

df = df.drop(columns=drop_cols, errors="ignore")

df = df.sort_values(by=["product_name", DATE_COL]).reset_index(drop=True)

LAGS = [1, 2, 3, 6]  # months

for lag in LAGS:
    df[f"lag_{lag}"] = (
        df.groupby("product_name")[TARGET]
        .shift(lag)
    )

WINDOWS = [3, 6]

for window in WINDOWS:
    df[f"rolling_mean_{window}"] = (
        df.groupby("product_name")[TARGET]
        .shift(1)
        .rolling(window)
        .mean()
    )

    df[f"rolling_std_{window}"] = (
        df.groupby("product_name")[TARGET]
        .shift(1)
        .rolling(window)
        .std()
    )

df = df.dropna().reset_index(drop=True)

FEATURES = [
    # Product & categorical
    "product_name",
    "product_type",
    "edition_type",
    "target_gender",
    "price_bucket",
    "sneaker_grade",

    # Time features
    "year",
    "month",
    "quarter",

    # Inventory & operations
    "total_produced",
    "units_received",
    "unsold_inventory",
    "damaged_units",
    "unit_price",
    "performance_score",

    # Lag features
    "lag_1", "lag_2", "lag_3", "lag_6",

    # Rolling features
    "rolling_mean_3", "rolling_std_3",
    "rolling_mean_6", "rolling_std_6",
]

X = df[FEATURES]
y = df[TARGET]

print("Final Feature Matrix Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nSample Features:")
print(X.head())

print("\nTarget Sample:")
print(y.head())

"""DATA SPLIT

"""

print("Date Range:")
print(df[DATE_COL].min(), "→", df[DATE_COL].max())

# Determine split date (last 6 months)
split_date = df[DATE_COL].max() - pd.DateOffset(months=6)

print("Train data up to:", split_date)
print("Test data after:", split_date)

# Train set (past)
train_df = df[df[DATE_COL] <= split_date]

# Test set (future)
test_df = df[df[DATE_COL] > split_date]

print("Train Shape:", train_df.shape)
print("Test Shape:", test_df.shape)

X_train = train_df[FEATURES]
y_train = train_df[TARGET]

X_test = test_df[FEATURES]
y_test = test_df[TARGET]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

# Ensure no future dates in training
assert train_df[DATE_COL].max() < test_df[DATE_COL].min()

print("✅ Time-series split verified. No data leakage.")

"""DATA MODEL - XGBOOST

"""

!pip install xgboost

import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
import matplotlib.pyplot as plt

xgb_model = xgb.XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100

print(f"RMSE : {rmse:.2f}")
print(f"MAE  : {mae:.2f}")
print(f"MAPE : {mape:.2f}%")

plt.figure(figsize=(10,5))
plt.plot(y_test.values, label="Actual", marker="o")
plt.plot(y_pred, label="Predicted", marker="x")
plt.title("XGBoost: Actual vs Predicted Demand")
plt.xlabel("Test Time Steps")
plt.ylabel("Total Sold")
plt.legend()
plt.show()

xgb.plot_importance(
    xgb_model,
    max_num_features=10,
    importance_type="gain",
    height=0.6
)
plt.title("Top Feature Importances (XGBoost)")
plt.show()

"""DATA-MODEL - LSTM"""

import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

import matplotlib.pyplot as plt

lstm_df = df[
    [
        "product_name",
        "snapshot_date",
        "total_sold",
        "unsold_inventory",
        "units_received"
    ]
].copy()

lstm_df = lstm_df.sort_values(
    ["product_name", "snapshot_date"]
).reset_index(drop=True)

from sklearn.preprocessing import MinMaxScaler

x_scaler = MinMaxScaler()
y_scaler = MinMaxScaler()

lstm_df[["unsold_inventory", "units_received"]] = x_scaler.fit_transform(
    lstm_df[["unsold_inventory", "units_received"]]
)

lstm_df[["total_sold"]] = y_scaler.fit_transform(
    lstm_df[["total_sold"]]
)

import numpy as np

SEQ_LEN = 6

def create_sequences_per_product(data, seq_len):
    X, y = [], []

    for product in data["product_name"].unique():
        product_data = data[data["product_name"] == product]

        values = product_data.values[:, 2:]  # exclude product & date

        if len(values) <= seq_len:
            continue

        for i in range(seq_len, len(values)):
            X.append(values[i-seq_len:i])
            y.append(values[i, 0])  # total_sold

    return np.array(X), np.array(y)

X_all, y_all = create_sequences_per_product(lstm_df, SEQ_LEN)

print("All sequences:", X_all.shape, y_all.shape)

# Explicitly force numeric dtype in LSTM features
numeric_cols = ["total_sold", "unsold_inventory", "units_received"]

lstm_df[numeric_cols] = lstm_df[numeric_cols].apply(
    pd.to_numeric, errors="coerce"
)

# Drop any rows that became NaN
lstm_df = lstm_df.dropna().reset_index(drop=True)

import numpy as np

def create_sequences_per_product(data, seq_len):
    X, y = [], []

    for product in data["product_name"].unique():
        product_data = data[data["product_name"] == product]

        # Use .loc and .to_numpy() with dtype
        values = product_data.loc[
            :, ["total_sold", "unsold_inventory", "units_received"]
        ].to_numpy(dtype=np.float32)

        if len(values) <= seq_len:
            continue

        for i in range(seq_len, len(values)):
            X.append(values[i-seq_len:i])
            y.append(values[i, 0])  # total_sold

    return np.array(X, dtype=np.float32), np.array(y, dtype=np.float32)

X_all, y_all = create_sequences_per_product(lstm_df, SEQ_LEN)

split_index = int(len(X_all) * 0.8)

X_train_lstm = X_all[:split_index]
y_train_lstm = y_all[:split_index]

X_test_lstm = X_all[split_index:]
y_test_lstm = y_all[split_index:]

print(X_train_lstm.dtype)
print(X_test_lstm.dtype)
print(y_train_lstm.dtype)
print(y_test_lstm.dtype)

##################################################################

split_index = int(len(X_all) * 0.8)

X_train_lstm = X_all[:split_index]
y_train_lstm = y_all[:split_index]

X_test_lstm = X_all[split_index:]
y_test_lstm = y_all[split_index:]

print("Train:", X_train_lstm.shape, y_train_lstm.shape)
print("Test :", X_test_lstm.shape, y_test_lstm.shape)

"""lstm implementation"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

history = model.fit(
    X_train_lstm,
    y_train_lstm,
    validation_split=0.2,
    epochs=100,
    batch_size=16,
    callbacks=[early_stop],
    verbose=1
)

y_pred_lstm = model.predict(X_test_lstm).flatten()

y_pred_lstm = model.predict(X_test_lstm).flatten()

y_test_inv = y_scaler.inverse_transform(y_test_lstm.reshape(-1, 1))
y_pred_inv = y_scaler.inverse_transform(y_pred_lstm.reshape(-1, 1))

rmse = np.sqrt(mean_squared_error(y_test_inv, y_pred_inv))
mae = mean_absolute_error(y_test_inv, y_pred_inv)
mape = np.mean(np.abs((y_test_inv - y_pred_inv) / y_test_inv)) * 100

print(rmse,"," ,mae,"," ,mape)

"""HYPERTUNNING XGBOOST"""

import xgboost as xgb
import numpy as np

from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit
from sklearn.metrics import mean_squared_error, make_scorer

tscv = TimeSeriesSplit(n_splits=5)

xgb_base = xgb.XGBRegressor(
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

param_dist = {
    "n_estimators": [200, 300, 400, 500],
    "max_depth": [3, 4, 5, 6, 8],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "subsample": [0.6, 0.7, 0.8, 0.9],
    "colsample_bytree": [0.6, 0.7, 0.8, 0.9],
    "min_child_weight": [1, 3, 5, 7]
}

rmse_scorer = make_scorer(
    lambda y_true, y_pred: np.sqrt(mean_squared_error(y_true, y_pred)),
    greater_is_better=False
)

random_search = RandomizedSearchCV(
    estimator=xgb_base,
    param_distributions=param_dist,
    n_iter=25,               # Efficient & sufficient
    scoring=rmse_scorer,
    cv=tscv,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)

print("Best Parameters Found:")
print(random_search.best_params_)

print("\nBest CV RMSE:")
print(-random_search.best_score_)

best_xgb_model = xgb.XGBRegressor(
    **random_search.best_params_,
    objective="reg:squarederror",
    random_state=42
)

best_xgb_model.fit(X_train, y_train)

y_pred_tuned = best_xgb_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred_tuned))
mae = np.mean(np.abs(y_test - y_pred_tuned))
mape = np.mean(np.abs((y_test - y_pred_tuned) / y_test)) * 100

print(f"Tuned XGBoost RMSE : {rmse:.2f}")
print(f"Tuned XGBoost MAE  : {mae:.2f}")
print(f"Tuned XGBoost MAPE : {mape:.2f}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.plot(y_test.values, label="Actual Demand", marker="o")
plt.plot(y_pred_tuned, label="Predicted Demand (Tuned XGBoost)", marker="x")

plt.title("Tuned XGBoost: Actual vs Predicted Demand")
plt.xlabel("Test Time Steps")
plt.ylabel("Total Units Sold")
plt.legend()
plt.grid(True)
plt.show()

"""DEMAND PREDICTION"""

# Last snapshot per product
last_df = (
    df.sort_values(["product_name", DATE_COL])
      .groupby("product_name")
      .tail(1)
      .reset_index(drop=True)
)

last_df[[DATE_COL, TARGET, "lag_1", "lag_2", "lag_3", "lag_6"]].head()

def create_future_row(row, next_date):
    new_row = row.copy()

    # Update date features
    new_row[DATE_COL] = next_date
    new_row["year"] = next_date.year
    new_row["month"] = next_date.month
    new_row["quarter"] = (next_date.month - 1) // 3 + 1

    # Shift lag features
    new_row["lag_6"] = new_row["lag_5"] if "lag_5" in new_row else new_row["lag_3"]
    new_row["lag_3"] = new_row["lag_2"]
    new_row["lag_2"] = new_row["lag_1"]
    new_row["lag_1"] = new_row[TARGET]

    return new_row

from pandas.tseries.offsets import DateOffset

future_forecasts = []

for product in last_df["product_name"].unique():

    product_row = last_df[last_df["product_name"] == product].iloc[0].copy()

    for step in range(1, 7):
        next_date = product_row[DATE_COL] + DateOffset(months=1)

        # Create future feature row
        future_row = create_future_row(product_row, next_date)

        # Prepare features
        X_future = future_row[FEATURES].values.reshape(1, -1)

        # Predict demand
        predicted_demand = best_xgb_model.predict(X_future)[0]

        # Save result
        future_forecasts.append({
            "product_name": product,
            "forecast_month": next_date,
            "predicted_demand": predicted_demand
        })

        # Update row for next iteration
        product_row[TARGET] = predicted_demand
        product_row[DATE_COL] = next_date
        product_row["lag_1"] = predicted_demand

forecast_df = pd.DataFrame(future_forecasts)

forecast_df.head(10)

# Latest inventory snapshot per product
inventory_df = (
    df.sort_values(["product_name", DATE_COL])
      .groupby("product_name")
      .tail(1)
      .reset_index(drop=True)
)

inventory_df = inventory_df[
    ["product_name", "unsold_inventory", "units_received"]
].rename(columns={
    "unsold_inventory": "current_inventory",
    "units_received": "last_received_units"
})

inventory_df.head()

forecast_summary = (
    forecast_df.groupby("product_name")["predicted_demand"]
    .agg(["mean", "std", "sum"])
    .reset_index()
)

forecast_summary.columns = [
    "product_name",
    "avg_monthly_demand",
    "demand_std",
    "six_month_demand"
]

forecast_summary.head()

Z = 1.65          # 95% service level
LEAD_TIME = 1    # 1 month

forecast_summary["safety_stock"] = (
    Z * forecast_summary["demand_std"] * np.sqrt(LEAD_TIME)
)

forecast_summary["reorder_point"] = (
    forecast_summary["avg_monthly_demand"] * LEAD_TIME
    + forecast_summary["safety_stock"]
)

inventory_plan = forecast_summary.merge(
    inventory_df,
    on="product_name",
    how="left"
)

inventory_plan["stock_gap"] = (
    inventory_plan["reorder_point"]
    - inventory_plan["current_inventory"]
)

REPLENISHMENT_COVERAGE = 2  # months

inventory_plan["recommended_order_qty"] = np.where(
    inventory_plan["stock_gap"] > 0,
    inventory_plan["avg_monthly_demand"] * REPLENISHMENT_COVERAGE
    - inventory_plan["current_inventory"],
    0
)

# No negative orders
inventory_plan["recommended_order_qty"] = (
    inventory_plan["recommended_order_qty"]
    .clip(lower=0)
    .round()
)

inventory_plan["order_required"] = np.where(
    inventory_plan["current_inventory"]
    <= inventory_plan["reorder_point"],
    "YES",
    "NO"
)

final_inventory_plan = inventory_plan[
    [
        "product_name",
        "current_inventory",
        "avg_monthly_demand",
        "safety_stock",
        "reorder_point",
        "recommended_order_qty",
        "order_required"
    ]
].sort_values("order_required", ascending=False)

final_inventory_plan.head(10)

plt.figure(figsize=(10,5))
plt.bar(
    final_inventory_plan["product_name"],
    final_inventory_plan["recommended_order_qty"]
)

plt.title("Recommended Order Quantity per Product")
plt.xlabel("Product")
plt.ylabel("Order Quantity")
plt.xticks(rotation=90)
plt.show()